package teach.vietnam.asia.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TBL_MAP_NAME.
 */
public class tblMapName {

    private String filename;
    private String sound;

    public tblMapName() {
    }

    public tblMapName(String filename) {
        this.filename = filename;
    }

    public tblMapName(String filename, String sound) {
        this.filename = filename;
        this.sound = sound;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getSound() {
        return sound;
    }

    public void setSound(String sound) {
        this.sound = sound;
    }

}
