package teach.vietnam.asia.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TBL_REC_JA.
 */
public class tblRecJA {

    private Integer group_id;
    private Integer word_id;
    private String vn;
    private String ex;
    private String ot;

    public tblRecJA() {
    }

    public tblRecJA(Integer group_id, Integer word_id, String vn, String ex, String ot) {
        this.group_id = group_id;
        this.word_id = word_id;
        this.vn = vn;
        this.ex = ex;
        this.ot = ot;
    }

    public Integer getGroup_id() {
        return group_id;
    }

    public void setGroup_id(Integer group_id) {
        this.group_id = group_id;
    }

    public Integer getWord_id() {
        return word_id;
    }

    public void setWord_id(Integer word_id) {
        this.word_id = word_id;
    }

    public String getVn() {
        return vn;
    }

    public void setVn(String vn) {
        this.vn = vn;
    }

    public String getEx() {
        return ex;
    }

    public void setEx(String ex) {
        this.ex = ex;
    }

    public String getOt() {
        return ot;
    }

    public void setOt(String ot) {
        this.ot = ot;
    }

}
